---

enabled: true

debug: false
#WARNING: Your log may get spammed.

block: 19
#Defualt is set to sponge (ID: 19)

economy: true
#Must have EconomyAPI for this to actually enable.
# ^^ set to true for LuckyBlocks to set money and set min & max values ^^

money_min: -500 #Will only work if economy is enabled and found.
money_max: 500

---
